- hosts:
  - ec2-k8s-m2
  become: yes
  tasks:
    - name: "Reset cluster"
      shell: "kubeadm reset -f"

    - name: "Fazendo join kubernetes master"
      shell: kubeadm join k8s-haproxy:6443 --token 9j9q14.ahnay2mq1dasrpgd  --discovery-token-ca-cert-hash sha256:0e5c656d9899ff1ded337b3799491634631d02a2418e8084edefa89fa0fa9607  --control-plane --certificate-key 49f83173624ab3f1997200c37749289aefe8cf46734f5bd3c422e0fa3c17c94c

    - name: "Colocando no path da maquina o conf do kubernetes"
      shell: mkdir -p /home/ubuntu/.kube && sudo cp -f /etc/kubernetes/admin.conf /home/ubuntu/.kube/config && sudo chown 1000:1000 /home/ubuntu/.kube/config && export KUBECONFIG=/etc/kubernetes/admin.conf
#---
- hosts:
  - ec2-k8s-w1
  - ec2-k8s-w2
  - ec2-k8s-w3
  - ec2-k8s-w4
  become: yes
  tasks:
    - name: "Reset cluster"
      shell: "kubeadm reset -f"

    - name: "Fazendo join kubernetes worker"
      shell: kubeadm join k8s-haproxy:6443 --token 9j9q14.ahnay2mq1dasrpgd  --discovery-token-ca-cert-hash sha256:0e5c656d9899ff1ded337b3799491634631d02a2418e8084edefa89fa0fa9607 

#---
- hosts:
  - ec2-k8s-m1
  become: yes
  tasks:
    - name: "Configura weavenet para reconhecer os nós master e workers"
      shell: kubectl apply -f "https://cloud.weave.works/k8s/net?k8s-version=$(kubectl version | base64 | tr -d '\n')"

    - name: Espera 30 segundos
      wait_for: timeout=30

    - shell: kubectl get nodes -o wide
      register: ps
    - debug:
        msg: " '{{ ps.stdout_lines }}' "
