apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-configmap-dev
data:
  USER: root
  # PASSWORD: {{ DB_PASSWORD }}
  DATABASE_URL: mysql://ec2-18-229-143-83.sa-east-1.compute.amazonaws.com:3306/SpringWebYoutubeTest?useTimezone=true&serverTimezone=UTC
  
  # DATABASE_URL: mysql://10.111.41.255:3306/SpringWebYoutubeTest?useTimezone=true&serverTimezone=UTC # caso esteja vinculando um clusterIP na mão
